<?php

namespace ClientBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getcommandebyuser($usercomd) {
        $qb = $this->createQueryBuilder("c");
        $qb->where("c.usercomd = :usercomd");
        $qb->setParameter("usercomd", $usercomd);

        return $qb->getQuery()->getResult();}
}
