<?php

namespace ClientBundle\Repository;

/**
 * ElementCmdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElementCmdRepository extends \Doctrine\ORM\EntityRepository
{
}
