<?php

namespace AppBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllorder()
    {
        $query = $this->getEntityManager()->createQuery("SELECT c FROM AppBundle:Commentaire  c  ORDER BY c.dateCreationCommentaire DESC ");
        return $query->getResult();
    }
}
