<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BilletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class newsletterRepository extends EntityRepository
{
    public function findAllNewsLettersActive( )
    {
        /*   $em = $this->getEntityManager();*/
        return $this->getEntityManager()
            ->createQuery('SELECT n
         FROM AppBundle:newsletter  n WHERE n.active = 1')
            ->getResult();
    }
}
