<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public function countAllUsers() {

        $qb = $this->createQueryBuilder("u");
        $qb->select("COUNT(u)");
        return $qb->getQuery()->getSingleScalarResult();

    }

    public function findAllorder()
    {
        $query = $this->getEntityManager()->createQuery("SELECT u FROM UserBundle:User  u  ORDER BY u.dateCreationCompte DESC ");
        return $query->getResult();
    }
}
